//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevTest1.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Required")]
        public string first_name { get; set; }

        [Required(ErrorMessage = "Required")]
        public string last_name { get; set; }

        [Required(ErrorMessage = "Required")]
        public string address { get; set; }

        [Required(ErrorMessage = "Required")]
        public string state { get; set; }

        [Required(ErrorMessage = "Required")]
        public string country { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<int> zip_code { get; set; }

        [Required(ErrorMessage = "Required")]
        public string phone_number { get; set; }

        [MaxLength(250, ErrorMessage = "Maximum limit of 250 characters exceeded")]
        public string note { get; set; }
    }
}
